POST http://127.0.0.1:1001/user/login
Content-Type: application/json

{
  "phone": "13500000000"
}

###
POST http://localhost:1001/user/loginVerification
Content-Type: application/json

{
  "phone": "13500000000",
  "verificationCode": "448868"
}

> {%
client.global.set("token", response.body.token);
 %}

###
GET http://localhost:1001/users
Authorization: {{token}}


###
GET http://localhost:1001/tanhua/todayBest
Authorization: {{token}}

###
GET http://localhost:1001/tanhua/recommendation
Authorization:{{token}}

###
GET http://localhost:1001/movements
Authorization: {{token}}

###
GET  http://localhost:1001/movements/all?userId=1
Authorization: {{token}}

###
GET http://localhost:1001/movements/recommend
Authorization: {{token}}

###
GET http://localhost:1001/comments?movementId=
Authorization: {{token}}

###
POST http://localhost:1001/comments
Authorization: {{token}}
Content-Type: application/json

{
  "movementId": "5e82dc406401952928c211cd",
  "comment": "测试评论"
}

###
GET http://localhost:1001/comments/5e82dc406401952928c211cd/dislike
Authorization: {{token}}

###
GET http://localhost:1001/comments/5e82dc406401952928c211cd/like
Authorization: {{token}}

###
GET http://localhost:1001/tanhua/cards
Authorization: {{token}}

