tanhua:
  sms:
    signName: 物流云商
    templateCode: SMS_106590012
    accessKeyId: LTAI4GKgob9vZ53k2SZdyAC7
    accessKeySecret: LHLBvXmILRoyw0niRSBuXBZewQ30la

  oos:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucketName: tanhua001
    url: https://tanhua001.oss-cn-beijing.aliyuncs.com/
    access-key-id: LTAI4GKgob9vZ53k2SZdyAC7
    access-key-secret: LHLBvXmILRoyw0niRSBuXBZewQ30la
  aip:
    appId: 24021388
    appKey: ZnMTwoETXnu4OPIGwGAO2H4G
    appSecretKey: D4jXShyinv5q26bUS78xRKgNLnB9IfZh
  hx:
    appKey: 1120211112118226#demo
    clientId: YXA6AGAtsusoSUKyw54lzXDNmw
    clientSecret: YXA6NbJuPMuqzZrYIjNLdbWEDJNpZc4

spring:
  application:
    name: tanhua-app-server
  redis:
    host: 192.168.136.160
    database: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 1ms
  cloud:
    nacos:
      server-addr: 192.168.136.160:8848
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  rabbitmq:
    host: 192.168.136.160
    port: 5672
    username: root
    password: root

dubbo:
  registry:
    address: nacos://192.168.136.160:8848
  consumer:
    timeout: 30000
fdfs:
  thumb-image:
    width: 150
    height: 150
  connect-timeout: 1500
  so-timeout: 1500
  tracker-list: 192.168.136.160:22122
  web-server-url: http://192.168.136.160:8888/



server:
  port: 1001
