spring:
  application:
    name: tanhua-gateway
  cloud:
    gateway:

      globalcors:

        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
      routes:
        # 探花系统
        - id: tanhua-app-server
          uri: lb://tanhua-app-server
          predicates:
            - Path=/app/**
          filters:
            - StripPrefix= 1
        # 后台系统
        - id: tanhua-admin
          uri: lb://tanhua-admin
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix= 1

    nacos:
      discovery:
        server-addr: 192.168.136.160:8848

server:
  port: 8888



gateway:
  excludedUrls: /user/login,/user/loginVerification,/system/users/verification,/system/users/login