server:
  port: 1002
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tanhua
    username: root
    password: asswecan
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: tanhua-dubbo-server

  cloud:
    nacos:
      server-addr: 127.0.0.1:8848

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
dubbo:
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: tanhua-app-server
