spring:
  application:
    name: tanhua-admin
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tanhua
    username: root
    password: asswecan
    driver-class-name: com.mysql.cj.jdbc.Driver


  rabbitmq:
    host: 192.168.136.160
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.136.160
    port: 6379
  cloud: #nacos配置
    nacos:
      discovery:
        server-addr: 192.168.136.160:8848
dubbo: #dubbo配置
  registry:
    address: spring-cloud://localhost
  consumer:
    check: false
    retries: 0
  protocols:
    dubbo:
      port: -1
tanhua:
  sms:
    signName: 物流云商
    templateCode: SMS_106590012
    accessKeyId: LTAI4GKgob9vZ53k2SZdyAC7
    accessKeySecret: LHLBvXmILRoyw0niRSBuXBZewQ30la

  oos:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucketName: tanhua001
    url: https://tanhua001.oss-cn-beijing.aliyuncs.com/
    access-key-id: LTAI4GKgob9vZ53k2SZdyAC7
    access-key-secret: LHLBvXmILRoyw0niRSBuXBZewQ30la
  aip:
    appId: 24021388
    appKey: ZnMTwoETXnu4OPIGwGAO2H4G
    appSecretKey: D4jXShyinv5q26bUS78xRKgNLnB9IfZh
  hx:
    appKey: 1120211112118226#demo
    clientId: YXA6AGAtsusoSUKyw54lzXDNmw
    clientSecret: YXA6NbJuPMuqzZrYIjNLdbWEDJNpZc4


  content:
    enable: true
    accessKeyID: LTAI4GKgob9vZ53k2SZdyAC7
    accessKeySecret: LHLBvXmILRoyw0niRSBuXBZewQ30la
    scenes: porn,terrorism #色情，暴力
#mybaits-plus
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_    #数据库表前缀
      id-type: auto        #数据库表主键的策略
